import React,{useState} from 'react'
import { useRouter } from 'next/router'
import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import SidebarWithHeader from './components/sidebar';
import styles from '../styles/Home.module.css'
import { Heading, Divider } from '@chakra-ui/react'
import Link from 'next/link';
import { StyledDashboard } from './components/styledDashboard';
export default function Home() {
    const router = useRouter();
    
  return (
<>
      <Head>
        <title>MediLedger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <SidebarWithHeader/>
    <StyledDashboard>
        <h1>Dashboard</h1>
    </StyledDashboard>
    <Divider/>
<p style={{color:"black"}}>textual data</p>
</>
  )
}
