import React,{useState} from 'react'
import { useRouter } from 'next/router'
import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import { Heading, Divider } from '@chakra-ui/react'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
    const router = useRouter();
    const [displayModal, setDisplayModal] = useState("none");
    const [message, setMessage] = useState("");
    const modalStyle= {
        position: "absolute",
        justifyContent: "center",
        display:displayModal,
        textAlign: "center",
        alignItems: "center",
            paddingTop:"35px",
            marginLeft: "38%",
            color: "black",
            width:"300px",
            height:"100px",
            borderRadius: "10px",
            backgroundColor: "#dcddde",
            transition:"0.3s ease-in-out",
        }
    
    const HandleSubmit = async(e) => {
        e.preventDefault();
        const cred = {email:e.target.email.value,password:e.target.password.value};
        console.log(cred)
        await axios.post("/api/login",cred)
        .then((data)=>{
            console.log(data)
            if(data.data.message === "User Found"){
            router.push('/dashboard');
            }
            else{
                setDisplayModal("block");
                setTimeout(() => {
                    setMessage("User not found");
                    setDisplayModal("none");
                }, 2000);
            }
        })
        .catch((error)=>{console.log(error.message)})
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>MediLedger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={modalStyle}> &nbsp;{message}&nbsp; </div>
      <img src='/logo.png' alt="logo" height={"260px"} width={"260px"} style={{margin:"auto",marginBottom:"-80px"}}/>
      <br/><br/><br/>
      <div className={styles.Formcontainer}>
        <h1 style={{margin:"auto",textAlign:"center"}}> Login </h1>
        <form className={styles.form} onSubmit={HandleSubmit}>
            <input className={styles.inputBox} type="email" name="email" placeholder="Email" />
            <input className={styles.inputBox} type="password" name="password" placeholder="Password" />
            <button className={styles.Button} type="submit">Login</button>
            <Link href="/signup" className={styles.Button} type="submit">Signup</Link>
        </form>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
