import React,{useState} from 'react'
import { useRouter } from 'next/router'
import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import { Heading, Divider } from '@chakra-ui/react'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
    const router = useRouter();
    
    const HandleSubmit = async(e) => {
        e.preventDefault();
        const cred = {email:e.target.email.value,password:e.target.password.value};
        await axios.post("/api/auth/login",cred)
            .then((data)=>{
                //router.push('/dashboard');
                console.log(data);
                console.log("render dot com");
            })
            .catch((error)=>{console.log(error)})
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>MediLedger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading as='h3' size='lg'>MediLedger v0.0.1</Heading>
      <br/><br/><br/>
      <div className={styles.Formcontainer}>
        <h1 style={{margin:"auto",textAlign:"center"}}> Login </h1>
        <form className={styles.form} onSubmit={HandleSubmit}>
            <input className={styles.inputBox} type="email" name="email" placeholder="Email" />
            <input className={styles.inputBox} type="password" name="password" placeholder="Password" />
            <button className={styles.Button} type="submit">Login</button>
            <Link href="/signup" className={styles.Button} type="submit">Signup</Link>
        </form>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
