import React,{useState} from 'react'
import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import { Heading, Divider } from '@chakra-ui/react'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import { useRouter } from 'next/router'

export default function Signup() {
    const router = useRouter();

    
    const HandleSubmit = async(e) => {
        e.preventDefault();
        const data = {
            name: e.target.name.value, licenseNo: e.target.licenseNo.value,
            nid: e.target.nid.value, userType: e.target.userType.value,
            email: e.target.email.value, phoneNo: e.target.phoneNumber.value,
            password: e.target.password.value
        }
        console.log(data);
        
        await axios.post("/api/tello",data)
            .then((data)=>{
                if(data.stats === 200){
                    router.push('/');
                    console.log(data);
                    }
                
            })
            .catch((error)=>{console.log(error.message)})
            
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>MediLedger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br/>
      
      <Heading as='h3' size='lg'>MediLedger v0.0.1</Heading>
      <br/><br/>
      <div className={styles.Formcontainer}>
        <h1 style={{margin:"auto",textAlign:"center"}}> Signup </h1>
        <br/>
        <form className={styles.form} onSubmit={HandleSubmit}>
            <input className={styles.inputBox} type="text" name="name" placeholder="Name Eg: John Doe" />
            <input className={styles.inputBox} type="text" name="licenseNo" placeholder="License Number" />
            <input className={styles.inputBox} type="text" name="nid" placeholder="NID Number" />
            <input className={styles.inputBox} type="email" name="email" placeholder="Email" />
            <input className={styles.inputBox} type="text" name="phoneNumber" placeholder="+8801000000" />
            <input className={styles.inputBox} type="password" name="password" placeholder="Password" />
            <input className={styles.inputBox} type="password" name="confirmPassword" placeholder="Confirm Password" />
            <input className={styles.inputBox} type="text" placeholder="User Type" />
            <label for="userType">User Type</label>
            <select className={styles.inputBox} name="userType">
                <option value="MANUFRACTURER">Manufracturer</option>
                <option value="SUPPLIER">Supplier</option>
                <option value="DISTRIBUTOR">Distributor</option>
                <option value="RETAILER">Retailer</option>
                <option value="CUSTOMER">Customer</option>
            </select>
            <button className={styles.Button} type="submit">Signup</button>
            <Link href="/" className={styles.Button} type="submit">Back to Login</Link>
        </form>
      </div>
      <br/><br/>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

    </div>
  )
}

/*
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      */
